### PR TITLE
Fix touch working on other players controls

### LINKED ISSUE #584: Able to control (UI only) things you shouldn't with touch
With touch controls you can set the other player following controls
you can also set them as a spectator

Rank Setting
Stage
Level

### PR DESCRIPTION
**Pull request by JamesVanBoxtel**
Fixes #584 by not having controls that are not yours enabled.

### CODE REVIEW

File: client/src/ui/ScrollContainer.lua [hunk 1]
```diff
@@ -139,7 +139,7 @@ end
 -- overwrite the default callback to always return itself so the class can act as an intermediator
 -- because any children that are offscreen at scrollOffset 0 cannot get hit by the default touchhandler without translating touch coordinates
 function ScrollContainer:getTouchedElement(x, y)
-  if self.isVisible and self.isEnabled and UiElement.inBounds(self, x, y) then
+  if self.isVisible and self.isEnabled and self:isTouchable() and UiElement.inBounds(self, x, y) then
```
Comment (Endaris) [inline client/src/ui/ScrollContainer.lua]: I'm removing this extra check because it adds verbosity without practical value.
Implementing its own `getTouchedElement` already implies touchability. With the touch callbacks being defined on the class, the only way to make a ScrollContainer not touchable is to make *all* ScrollContainers untouchable which makes no sense.

**Review by Endaris — APPROVED** [review]
Thanks, did not think of doing it like this.
I added a disable for character buttons as well ~~but I have not been able to test it yet due to lack of spectatable matches so I'm holding the merge until later today.~~ Nevermind
